// src/types/api.ts
// TypeScript interfaces for API requests and responses
// Matches backend schema definitions

// ============================================
// User Types
// ============================================

export interface User {
  id: string;
  email: string;
  name: string;
  profilePictureUrl: string | null;
}

// ============================================
// Auth Types
// ============================================

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  profilePictureUrl?: string | null;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface AuthResponse {
  success: true;
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: User;
}

export interface RefreshResponse {
  success: true;
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface MeResponse {
  success: true;
  user: User;
}

export interface LogoutResponse {
  success: true;
  message: string;
}

// ============================================
// Photo Types
// ============================================

// Photo as returned from list endpoint
export interface Photo {
  id: string;
  filename: string;
  originalName: string;
  uploadedAt: string;
  width: number | null;
  height: number | null;
  thumbnailUrl: string;
  fileUrl: string;
  tags?: PhotoTag[];
}

// Photo with full details (from get single photo)
export interface PhotoDetail extends Photo {
  userId: string;
  groupId: string | null;
  mimeType: string;
  fileSize: number;
  takenAt: string | null;
}

// Simplified tag format from list endpoint
export interface PhotoTag {
  id: string;
  tag: string;
  confidence: number;
  category: string;
}

// Full AI tag with ID
export interface AiTag {
  id: string;
  photoId: string;
  tag: string;
  confidence: number;
  category: string;
}

export interface PhotosResponse {
  success: true;
  photos: Photo[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
  };
}

export interface PhotoResponse {
  success: true;
  photo: PhotoDetail;
}

export interface UploadResponse {
  success: true;
  message: string;
  photos: Array<{
    id: string;
    filename: string;
    originalName: string;
    uploadedAt: string;
    thumbnailUrl: string;
  }>;
}

// ============================================
// Album Types
// ============================================

export interface Album {
  id: string;
  name: string;
  description: string | null;
  userId: string;
  groupId: string | null;
  isAutoGenerated: boolean;
  generationCriteria: string | null;
  createdAt: string;
  updatedAt: string;
  _count?: {
    photos: number;
  };
}

// ============================================
// Group Types
// ============================================

export interface Group {
  id: string;
  name: string;
  description: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  _count?: {
    members: number;
    photos: number;
  };
}

export interface GroupMembership {
  id: string;
  groupId: string;
  userId: string;
  role: 'owner' | 'admin' | 'member';
  joinedAt: string;
  user?: User;
}

// ============================================
// Error Types
// ============================================

export interface ApiError {
  success: false;
  error: string;
  code: string;
}

// Common error codes from backend
export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'INVALID_CREDENTIALS'
  | 'USER_EXISTS'
  | 'USER_NOT_FOUND'
  | 'NO_TOKEN'
  | 'TOKEN_EXPIRED'
  | 'INVALID_TOKEN'
  | 'REFRESH_TOKEN_EXPIRED'
  | 'INVALID_REFRESH_TOKEN'
  | 'MISSING_TOKEN'
  | 'RATE_LIMIT_EXCEEDED'
  | 'NOT_FOUND'
  | 'FORBIDDEN'
  | 'INTERNAL_ERROR';

// ============================================
// AI Analysis Types
// ============================================

export interface AnalyzeResponse {
  success: true;
  message: string;
  tags: PhotoTag[];
}

export interface AddTagResponse {
  success: true;
  tag: PhotoTag;
}

export interface RemoveTagResponse {
  success: true;
  message: string;
}
