// src/types/api.ts
// TypeScript interfaces for API requests and responses
// Matches backend schema definitions

// ============================================
// User Types
// ============================================

export interface User {
  id: string;
  email: string;
  name: string;
  profilePictureUrl: string | null;
}

// ============================================
// Auth Types
// ============================================

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  profilePictureUrl?: string | null;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface AuthResponse {
  success: true;
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: User;
}

export interface RefreshResponse {
  success: true;
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface MeResponse {
  success: true;
  user: User;
}

export interface LogoutResponse {
  success: true;
  message: string;
}

// ============================================
// Photo Types
// ============================================

// Photo as returned from list endpoint
export interface Photo {
  id: string;
  filename: string;
  originalName: string;
  uploadedAt: string;
  width: number | null;
  height: number | null;
  thumbnailUrl: string;
  fileUrl: string;
  tags?: PhotoTag[];
}

// Photo with full details (from get single photo)
export interface PhotoDetail extends Photo {
  userId: string;
  groupId: string | null;
  mimeType: string;
  fileSize: number;
  takenAt: string | null;
}

// Simplified tag format from list endpoint
export interface PhotoTag {
  id: string;
  tag: string;
  confidence: number;
  category: string;
}

// Full AI tag with ID
export interface AiTag {
  id: string;
  photoId: string;
  tag: string;
  confidence: number;
  category: string;
}

export interface PhotosResponse {
  success: true;
  photos: Photo[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
  };
}

export interface PhotoResponse {
  success: true;
  photo: PhotoDetail;
}

export interface UploadResponse {
  success: true;
  message: string;
  photos: Array<{
    id: string;
    filename: string;
    originalName: string;
    uploadedAt: string;
    thumbnailUrl: string;
    faces?: Face[]; // Only present when detectFaces=true is passed to upload
  }>;
}

// ============================================
// Album Types
// ============================================

export interface Album {
  id: string;
  name: string;
  description: string | null;
  userId: string;
  groupId: string | null;
  isAutoGenerated: boolean;
  generationCriteria: string | null;
  createdAt: string;
  updatedAt: string;
  _count?: {
    photos: number;
  };
}

// ============================================
// Group Types
// ============================================

export interface Group {
  id: string;
  name: string;
  description: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  _count?: {
    members: number;
    photos: number;
  };
}

export interface GroupMembership {
  id: string;
  groupId: string;
  userId: string;
  role: 'owner' | 'admin' | 'member';
  joinedAt: string;
  user?: User;
}

// ============================================
// Error Types
// ============================================

export interface ApiError {
  success: false;
  error: string;
  code: string;
}

// Common error codes from backend
export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'INVALID_CREDENTIALS'
  | 'USER_EXISTS'
  | 'USER_NOT_FOUND'
  | 'NO_TOKEN'
  | 'TOKEN_EXPIRED'
  | 'INVALID_TOKEN'
  | 'REFRESH_TOKEN_EXPIRED'
  | 'INVALID_REFRESH_TOKEN'
  | 'MISSING_TOKEN'
  | 'RATE_LIMIT_EXCEEDED'
  | 'NOT_FOUND'
  | 'FORBIDDEN'
  | 'INTERNAL_ERROR';

// ============================================
// AI Analysis Types
// ============================================

export interface AnalyzeResponse {
  success: true;
  message: string;
  tags: PhotoTag[];
}

export interface AddTagResponse {
  success: true;
  tag: PhotoTag;
}

export interface RemoveTagResponse {
  success: true;
  message: string;
}

// ============================================
// Face & People Types (AWS Rekognition)
// ============================================

// Bounding box coordinates as percentages (0-1)
export interface BoundingBox {
  left: number; // % from left edge (0-1)
  top: number; // % from top edge (0-1)
  width: number; // % of image width (0-1)
  height: number; // % of image height (0-1)
}

// Match suggestion for a detected face
export interface FaceMatchSuggestion {
  personId: string;
  personName: string | null;
  similarity: number;
}

// Individual face detected in a photo (as returned by getFaces/detectFaces endpoints)
export interface Face {
  id: string;
  boundingBox: BoundingBox;
  confidence: number;
  indexed: boolean;
  person?: { id: string; name: string | null } | null;
  match?: FaceMatchSuggestion | null; // Suggestion for 80-90% matches (null from getFaces, present from detectFaces)
}

// Person in user's face collection
export interface Person {
  id: string;
  name: string | null;
  collectionId: string;
  createdAt: string;
  updatedAt: string;
  _count?: { faces: number };
}

// API Responses - matching backend controller responses

export interface FaceDetectionResponse {
  success: true;
  message: string;
  faces: Face[];
}

export interface FacesResponse {
  success: true;
  faces: Face[];
}

export interface TagFaceResponse {
  success: true;
  face: {
    id: string;
    indexed: boolean;
    awsFaceId: string | null;
  };
  person: {
    id: string;
    name: string | null;
  };
}

// Person as returned from list endpoint (different from full Person model)
export interface PersonListItem {
  id: string;
  name: string | null;
  photoCount: number;
  createdAt: string;
}

export interface PeopleResponse {
  success: true;
  people: PersonListItem[];
  pagination: {
    limit: number;
    offset: number;
    total: number;
  };
}

export interface PersonResponse {
  success: true;
  person: {
    id: string;
    name: string | null;
    photoCount: number;
    createdAt: string;
    updatedAt: string;
  };
}

// Simplified photo for list views (person photos, etc.)
export interface PhotoListItem {
  id: string;
  filename: string;
  originalName: string;
  thumbnailUrl: string;
  uploadedAt: string;
}

export interface PersonPhotosResponse {
  success: true;
  photos: PhotoListItem[];
}

// ============================================
// Bulk Operations Types
// ============================================

// Result for a single photo in bulk operations
export interface BulkPhotoResult {
  photoId: string;
  success: boolean;
  error?: string;
}

export interface BulkAnalyzeResponse {
  success: true;
  message: string;
  results: BulkPhotoResult[];
  summary: {
    total: number;
    succeeded: number;
    failed: number;
  };
}

export interface BulkDetectFacesResponse {
  success: true;
  message: string;
  results: Array<{
    photoId: string;
    success: boolean;
    facesDetected?: number;
    error?: string;
  }>;
  summary: {
    total: number;
    succeeded: number;
    failed: number;
    totalFacesDetected: number;
  };
}

export interface BulkDeleteResponse {
  success: true;
  message: string;
  results: BulkPhotoResult[];
  summary: {
    total: number;
    succeeded: number;
    failed: number;
  };
}
